info:
  contact: {}
  title: v1
  version: Version
  description: ''
paths:
  /:
    get:
      consumes:
        - application/json
      description: Print Hello World!
      operationId: hello
      produces:
        - application/json
      responses:
        '201':
          description: Created
          schema:
            type: string
        '400':
          description: errorMessage
          schema:
            type: string
        '500':
          description: errorMessage
          schema:
            type: string
      summary: Print Hello World!
      tags:
        - hello
  /bye:
    get:
      consumes:
        - application/json
      description: Print Bye World!
      operationId: bye
      produces:
        - application/json
      responses:
        '201':
          description: Created
          schema:
            type: string
        '400':
          description: errorMessage
          schema:
            type: string
        '500':
          description: errorMessage
          schema:
            type: string
      summary: Print Hello World!
      tags:
        - hello
    parameters: []
swagger: '2.0'
schemes:
  - http
  - https
host: 'localhost:8085'
x-internal: false
