version: '3.9'
services:
  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/swagger.yaml'
    volumes:
      - ../swagger.yaml:/tmp/swagger.yaml:ro
    ports:
      # Serve the mocked API locally as available on port 8080
      - '5000:4010'